#!/bin/bash

echo "[II] Installing APT packages..."
wget -O - https://downloads.spellchecker.lu/packages/Ubuntu/pubkey.asc | sudo apt-key add -
sudo wget https://downloads.spellchecker.lu/packages/Ubuntu/spellchecker_lu.list -O /etc/apt/sources.list.d/spellchecker_lu.list
sudo apt-get install aptitude
sudo aptitude update
sudo aptitude install \
    build-essential \
    git \
    hunspell-lb-lu \
    irssi \
    keepassx \
    keychain \
    libpq-dev \
    mplayer \
    mythes-lb \
    poedit \
    python-dev \
    python-pip \
    tmux \
    tree \
    vim-gnome \
    vim-gtk \
    zsh

sudo pip install \
    fabric \
    pip \
    virtualenv

. bootstrap_common

if [[ ! -f "$HOME/.dropbox-dist/dropboxd" ]]; then
    echo "[II] installing dropbox..."
    (cd ~ && wget -q -O - "https://www.dropbox.com/download?plat=lnx.$(uname -m)" | tar xzf -)
else
    echo "[II] dropbox already installed"
fi

if [[ "$SHELL" != "/usr/bin/zsh" && -e /usr/bin/zsh ]]; then
    echo "[II] Changing login-shell..."
    chsh
else
    echo "[II] Already on zsh, or zsh not available on this system"
fi

if [[ ! -d "$HOME/.fonts" ]]; then
    echo "[II] installing powerline fonts..."
    (cd /tmp && git clone https://github.com/powerline/fonts && cd fonts && ./install.sh)
else
    echo "[II] fonts already installed"
fi

. decellerate_mouse.bash
