#!/bin/bash

echo "[II] Installing APT packages..."
sudo apt update
sudo apt install -y \
    tmux \
    tree \
    vim-nox \
    zsh

. bootstrap_common

if [[ "$SHELL" != "/usr/bin/zsh" && -e /usr/bin/zsh ]]; then
    echo "[II] Changing login-shell..."
    chsh
else
    echo "[II] Already on zsh, or zsh not available on this system"
fi
