#!/bin/bash

set -e

echo "[II] Installing APT packages..."
sudo apt-get install aptitude
sudo aptitude -q -q update
sudo aptitude -q -q install \
    python3-venv \
    build-essential \
    git \
    irssi \
    keepassx \
    keychain \
    libpq-dev \
    mplayer \
    poedit \
    python3-dev \
    python3-pip \
    tmux \
    tree \
    vim-nox \
    zsh

pip install --user \
    pip \
    pipx

~/.local/bin/pipx install fabric

. bootstrap_common

if [[ "$SHELL" != "/usr/bin/zsh" && -e /usr/bin/zsh ]]; then
    echo "[II] Changing login-shell..."
    chsh
else
    echo "[II] Already on zsh, or zsh not available on this system"
fi

if [[ ! -d "$HOME/.fonts" ]]; then
    echo "[II] installing powerline fonts..."
    (cd /tmp && git clone https://github.com/powerline/fonts && cd fonts && ./install.sh)
else
    echo "[II] fonts already installed"
fi
