#!/bin/bash

echo "[II] Installing APT packages..."
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get install aptitude
sudo aptitude -q -q update
sudo aptitude -q -q install \
    build-essential \
    git \
    irssi \
    keepassx \
    keychain \
    libpq-dev \
    mplayer \
    oracle-java7-installer \
    poedit \
    python-dev \
    python-pip \
    tmux \
    tree \
    vim-nox \
    zsh

pip install --user \
    pip \
    fabric

. bootstrap_common

if [[ ! -f "$HOME/.dropbox-dist/dropboxd" ]]; then
    echo "[II] installing dropbox..."
    (cd ~ && wget -q -O - "https://www.dropbox.com/download?plat=lnx.$(uname -m)" | tar xzf -)
else
    echo "[II] dropbox already installed"
fi

if [[ "$SHELL" != "/usr/bin/zsh" && -e /usr/bin/zsh ]]; then
    echo "[II] Changing login-shell..."
    chsh
else
    echo "[II] Already on zsh, or zsh not available on this system"
fi

if [[ ! -d "$HOME/.fonts" ]]; then
    echo "[II] installing powerline fonts..."
    (cd /tmp && git clone https://github.com/powerline/fonts && cd fonts && ./install.sh)
else
    echo "[II] fonts already installed"
fi

. decellerate_mouse.bash

