#!/bin/bash

echo "[II] Installing APT packages..."
sudo apt-get install aptitude
sudo aptitude install \
    git \
    irssi \
    keepassx \
    vim-gnome \
    keychain \
    zsh \
    mplayer

if [[ ! -f "$HOME/.dropbox-dist/dropboxd" ]]; then
    echo "[II] installing dropbox..."
    (cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86" | tar xzf -)
else
    echo "[II] dropbox already installed"
fi

if [[ "$SHELL" != "/usr/bin/zsh" && -e /usr/bin/zsh ]]; then
    chsh
else
    echo "[II] Already on zsh, or zsh not available on this system"
fi
