#!/bin/bash
# ---------------------------------------------------------------------------
# Script to install these dotfiles into the current user's home.
#
# WARNING: This *will* overwrite existing files!
# ---------------------------------------------------------------------------

cd
[ -d .irssi ] && rm -rf .irssi
[ -d .oh-my-zsh ] && rm -rf .oh-my-zsh
[ -d .psql_history ] || mkdir .psql_history
[ -f .Xdefaults ] && rm .Xdefaults
[ -f .bashrc ] && rm .bashrc
[ -f .bashrc_BBS-goon ] && rm .bashrc_BBS-goon
[ -f .digrc ] && rm .digrc
[ -f .gitconfig ] && rm .gitconfig
[ -f .gitignore ] && rm .gitignore
[ -f .inputrc ] && rm .inputrc
[ -f .minttyrc ] && rm .minttyrc
[ -f .psql_history ] && mv -v .psql_history .psql_history.bak
[ -f .psql_history.bak ] && mv -v .psql_history.bak .psql_history/old-single-file-history
[ -f .psqlrc ] && rm .psqlrc
[ -f .pylintrc ] && rm .pylintrc
[ -f .pystartup ] && rm .pystartup
[ -f .tmux.conf ] && rm .tmux.conf
[ -f .zshrc ] && rm .zshrc
[ -f .zshrc_blackdragon ] && rm .zshrc_blackdragon
[ -f .zshrc_lillend ] && rm .zshrc_lillend
[ -s .xinitrc ] && rm .xinitrc
[ -s .Xmodmap ] && rm .Xmodmap
[ -s .i3 ] && rm -rf .i3

ln -vs dotfiles/.psqlrc
ln -vs dotfiles/.irssi
ln -vs dotfiles/.bashrc
ln -vs dotfiles/.bashrc_BBS-goon
ln -vs dotfiles/.digrc
ln -vs dotfiles/.gitconfig
ln -vs dotfiles/.gitignore_global .gitignore
ln -vs dotfiles/.inputrc
ln -vs dotfiles/.pylintrc
ln -vs dotfiles/.pystartup
ln -vs dotfiles/.tmux.conf
ln -vs dotfiles/.Xdefaults
ln -vs dotfiles/.zshrc
ln -vs dotfiles/.zshrc_blackdragon
ln -vs dotfiles/.zshrc_lillend
ln -vs dotfiles/.minttyrc
ln -vs dotfiles/.xinitrc
ln -vs dotfiles/.i3
git clone https://github.com/exhuma/oh-my-zsh.git .oh-my-zsh

read -sp "[IRSSI] FreeNode Password: " IRSSI_PASSWORD
cat dotfiles/.irssi/config.template | \
    sed -e "s/{{password}}/${IRSSI_PASSWORD}/" \
    > .irssi/config
echo

HOSTNAME=$(hostname -s)
echo Installing overlay for $HOSTNAME

if [ -d dotfiles/${HOSTNAME}/.kde/Autostart ]; then
    rm -rf .kde/Autostart
    ln -vs ~/dotfiles/${HOSTNAME}/.kde/Autostart ~/.kde/Autostart
fi

if [ -f dotfiles/${HOSTNAME}/.Xmodmap ]; then
    ln -vs dotfiles/${HOSTNAME}/.Xmodmap
fi

echo done!
