#!/bin/bash
# ---------------------------------------------------------------------------
# Script to install these dotfiles into the current user's home.
#
# WARNING: This *will* overwrite existing files!
# ---------------------------------------------------------------------------

cd
[ -f .bashrc ] && rm .bashrc
[ -f .bashrc_BBS-goon ] && rm .bashrc_BBS-goon
[ -f .digrc ] && rm .digrc
[ -f .gitconfig ] && rm .gitconfig
[ -f .gitignore ] && rm .gitignore
[ -f .inputrc ] && rm .inputrc
[ -f .pylintrc ] && rm .pylintrc
[ -f .pystartup ] && rm .pystartup
[ -f .tmux.conf ] && rm .tmux.conf
[ -f .Xdefaults ] && rm .Xdefaults
[ -f .zshrc ] && rm .zshrc
[ -f .zshrc_blackdragon ] && rm .zshrc_blackdragon
[ -f .zshrc_lillend ] && rm .zshrc_lillend
[ -d .irssi ] && rm -rf .irssi
[ -d .oh-my-zsh ] && rm -rf .oh-my-zsh
ln -vs dotfiles/.irssi
ln -vs dotfiles/.bashrc
ln -vs dotfiles/.bashrc_BBS-goon
ln -vs dotfiles/.digrc
ln -vs dotfiles/.gitconfig
ln -vs dotfiles/.gitignore_global .gitignore
ln -vs dotfiles/.inputrc
ln -vs dotfiles/.pylintrc
ln -vs dotfiles/.pystartup
ln -vs dotfiles/.tmux.conf
ln -vs dotfiles/.Xdefaults
ln -vs dotfiles/.zshrc
ln -vs dotfiles/.zshrc_blackdragon
ln -vs dotfiles/.zshrc_lillend
git clone https://github.com/exhuma/oh-my-zsh.git .oh-my-zsh

read -sp "[IRSSI] FreeNode Password: " IRSSI_PASSWORD
cat dotfiles/.irssi/config.template | \
    sed -e "s/{{password}}/${IRSSI_PASSWORD}/" \
    > .irssi/config

echo done!
